Add popup menu: Release
manq2010/my-portfolio pull request #12
Opened 2022-10-11 22:11 UTC by manq2010

Portfolio: details popup window
--- 
In this release, the following was done:
* Added popup window for both mobile and desktop

2022-10-11 22:54 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Hey @manq2010, @mkaya13, @yonas44 :wave:

## Highlights :1st_place_medal:

:heavy_check_mark: Descriptive PR Title
:heavy_check_mark: Descriptive PR Summary
:heavy_check_mark: Following Linters
:heavy_check_mark: Following some requirements

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-11 22:54 UTC, HAMMAS-SALEEM commented on index.html
>          </fieldset>
- [ ] Kindly comment all your project cards from your html file generate these cards from your **JavaScript** dynamically by using the array of objects which you have made in your **JavaScript** file :+1:

2022-10-11 22:54 UTC, HAMMAS-SALEEM commented on index.html
> +    </section>
- [ ] Kindly remove modal card from your html file generate this modal card from your **JavaScript** dynamically by using the array of objects which you have made in your **JavaScript** file :+1:

2022-10-11 22:54 UTC, HAMMAS-SALEEM commented on index.html
>          </fieldset>
### Your Desktop Modal
![image](https://user-images.githubusercontent.com/93039359/195211590-5488fc01-18ff-4295-b1d0-c12be36c07f5.png)

### Your Mobile Modal
![image](https://user-images.githubusercontent.com/93039359/195212563-c0dca369-551f-4303-95da-3674dd063af1.png)


- [ ] You have created your modal window but your modal window design is not very fit on the screen cuz you can see there is a horizontal scrollbar. Kindly fix your design in both desktop and mobile version :+1:

2022-10-12 06:42 UTC, manq2010 commented on index.html
>          </fieldset>
Please see how the design looks on my side... I used `inspect` and set it to the correct one with i.e for desktop set it the given `1440px` to mimic the figma design  :blush: :blush:

[My previous reviewer mentioned I do the same](https://github.com/manq2010/my-portfolio/pull/6) :blush: :blush:

![image](https://user-images.githubusercontent.com/53082877/195266526-42f6b911-8568-4450-9fd3-2f99074a517e.png)

Desktop Modal opened
---
![image](https://user-images.githubusercontent.com/53082877/195267197-75bac52d-fce7-4494-8850-2bc741c0ca47.png)

Mobile Version
---
![image](https://user-images.githubusercontent.com/53082877/195267564-f2dc8122-246a-4f3c-b550-4c4f06fbd918.png)

![image](https://user-images.githubusercontent.com/53082877/195267691-e4eb21b0-5fc9-4b20-8e93-b71b04c9e25e.png)

2022-10-12 09:54 UTC, manq2010 commented on index.html
> +    </section>
I think this code might improve the code to make it dynamic which is achieved by not putting the modal part of HTML on **javascript**. When I put the modal part of HTML on **javascript**, the callback events are not responsive. Perhaps you can assist with a different approach if the one just submitted does not meet the requirements.

```js
buttons.forEach((btn, index) => {
  btn.addEventListener('click', () => {
    modalContainer.style.display = 'block';
    title.innerHTML = cardContainer[index].title;
    modalPicture.style.background = `url(
    ${cardContainer[index].image[0]}) no-repeat center center/ cover`;
    modalPictureDesktop.style.background = `url(
      ${cardContainer[index].image[1]}) no-repeat center center/ cover`;

    projectDetails.innerHTML = cardContainer[index].projectDetails;

    while (codingLanguages.hasChildNodes()) {
      codingLanguages.removeChild(codingLanguages.firstChild);
    }

    cardContainer[index].codingLanguages.map((lang) => {
      const language = document.createElement('li');
      language.innerHTML = lang;
      codingLanguages.appendChild(language);
      return '';
    });

    link1.setAttribute('href', cardContainer[index].liveDemo);
    link2.setAttribute('href', cardContainer[index].liveSource);
  });
});

```

2022-10-12 11:10 UTC, manq2010 commented
For Reference
---

**Desktop view**
![image](https://user-images.githubusercontent.com/53082877/195327672-6dfecb5e-ac23-438d-b371-a056bb5f449a.png)

2022-10-12 11:13 UTC, manq2010 commented
The figma one is also at 1440px width
---

![image](https://user-images.githubusercontent.com/53082877/195328336-513961b8-04a9-410b-b2e9-46b572127c7e.png)

2022-10-12 12:53 UTC, ahmetbozaci reviewed
### Hello @manq2010 
### _This is an additional review as a result of the second opinion request._ 
![1](https://media.giphy.com/media/xT5LMScZteTtJ1j5q8/giphy.gif)

**I checked your project at 1440px width.**

- This is what looks like after this commit `Update JS to be dynamic`. It is not centered. Near to right side.
### Desktop version
![image](https://user-images.githubusercontent.com/38635158/195347255-f7ace25e-e7f9-4379-a19a-b3493bb300ee.png)

- Updated version(after this commit `Update card position`). It is not centered. Near to the left side.
### Desktop version
![image](https://user-images.githubusercontent.com/38635158/195347335-7b6f1c6c-762e-4775-af12-66ab313c5bba.png)
**As you can see the desktop version is not still centered. No issue with the mobile version.**

Kindly work on this issue and submit it for review after you have done.







___

### Cheers and Happy coding! 💻 👏
____
[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2022-10-13 12:10 UTC, merged